### ISSUE TITLE
Missing libraries in ubuntu medium image prevent dotnet core from running tests

### ISSUE THREAD

**Issue by mauricel** [catthehacker/docker_images#2]
Thank you for act and the awesome set of default images to go with it. I'm still new to GitHub actions, so being able to play around locally gives me a bit of extra confidence.

I ran into a error (logs below) with act and the Medium image. I think there are some libraries missing that are needed by dotnet. The repository I was using act with is https://github.com/Tyrrrz/CliFx

I was able to work around the error by setting the environment variable DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=1 (ref https://github.com/dotnet/core/issues/2186) to the github action. I might take a look later regarding what needs to happen to the docker image to fix, but thought I'd give you a heads up.

Thanks for the great work!

```
[CI/build-1] ⭐  Run Install .NET
[CI/build-1]   ☁  git clone 'https://github.com/actions/setup-dotnet' # ref=v1.7.2
[CI/build-1]   🐳  docker cp src=act/actions-setup-dotnet@v1.7.2 dst=/actions/
| [command]/actions/actions-setup-dotnet@v1.7.2/externals/install-dotnet.sh --version 5.0.103
| dotnet_install: Warning: Unable to locate zlib. Probable prerequisite missing; install zlib.
| dotnet_install: Warning: Unable to locate libicu. Probable prerequisite missing; install libicu.
| dotnet_install: Warning: Unable to locate liblttng. Probable prerequisite missing; install libcurl.
| dotnet-install: Downloading link: https://dotnetcli.azureedge.net/dotnet/Sdk/5.0.103/dotnet-sdk-5.0.103-linux-x64.tar.gz
| dotnet-install: Extracting zip from https://dotnetcli.azureedge.net/dotnet/Sdk/5.0.103/dotnet-sdk-5.0.103-linux-x64.tar.gz
| dotnet-install: Adding to current process PATH: `/github/home/.dotnet`. Note: This change will be visible only when sourcing script.
| dotnet-install: Installation finished successfully.
[CI/build-1]   ⚙  ::add-path:: /github/home/.dotnet
| /github/home/.dotnet:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
[CI/build-1]   ❓  ##[add-matcher]/actions/actions-setup-dotnet@v1.7.2/.github/csc.json
[CI/build-1]   ✅  Success - Install .NET
[CI/build-1] ⭐  Run Build & test
| Process terminated. Couldn't find a valid ICU package installed on the system. Set the configuration flag System.Globalization.Invariant to true if you want to run with no globalization support.
|    at System.Environment.FailFast(System.String)
|    at System.Globalization.GlobalizationMode.GetGlobalizationInvariantMode()
|    at System.Globalization.GlobalizationMode..cctor()
|    at System.Globalization.CultureData.CreateCultureWithInvariantData()
|    at System.Globalization.CultureData.get_Invariant()
|    at System.Globalization.CultureInfo..cctor()
|    at System.IO.TextWriter..cctor()
|    at System.IO.StreamWriter..ctor(System.IO.Stream, System.Text.Encoding, Int32, Boolean)
|    at System.Console.CreateOutputWriter(System.IO.Stream)
|    at System.Console.<get_Out>g__EnsureInitialized|25_0()
|    at System.Console.get_Out()
|    at Microsoft.DotNet.Cli.Utils.Reporter.Reset()
|    at Microsoft.DotNet.Cli.Utils.Reporter..cctor()
|    at Microsoft.DotNet.Cli.Utils.Reporter.get_Output()
|    at Microsoft.DotNet.Cli.Program.ConfigureDotNetForFirstTimeUse(Microsoft.DotNet.Configurer.IFirstTimeUseNoticeSentinel, Microsoft.DotNet.Configurer.IAspNetCertificateSentinel, Microsoft.DotNet.Configurer.IFileSentinel, Boolean, Microsoft.DotNet.Configurer.DotnetFirstRunConfiguration, Microsoft.DotNet.Cli.Utils.IEnvironmentProvider)
|    at Microsoft.DotNet.Cli.Program.ProcessArgs(System.String[], Microsoft.DotNet.Cli.Telemetry.ITelemetry)
|    at Microsoft.DotNet.Cli.Program.Main(System.String[])
| /github/workflow/2: line 1:   223 Aborted                 dotnet test --configuration Release --logger GitHubActions
[CI/build-1]   ❌  Failure - Build & test
Error: exit with `FAILURE`: 134
```

**Comment by catthehacker** [comment]
I will have to check how much space it takes but most likely I will include those libraries in the image.
